config/routes.rb
Rails.application.routes.draw do
  get 'application/infos'
  get 'application/contact'
  get 'application/rules'
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index, :show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/controllers/tags_controller.rb
# Manage event and organisation tags
class TagsController < InheritedResources::Base
  has_scope :region, :locality, :daylimit
  has_scope :period, type: :hash, using: [:year, :week]
  has_scope :tag, as: :id

  def index
    @tags = organise_tags apply_scopes(Event.moderated)

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end
  end

  def show
    @events_future = apply_scopes(Event).moderated.future
    @events_past = apply_scopes(Event).moderated.past

    respond_to do |format|
      format.html
      format.json { render json: @events_future + @events_past }
    end
  end

  def orgas
    @tags = organise_tags apply_scopes(Orga.moderated)

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end
  end

  private

  # Splits, groups, rejects the less used
  def organise_tags(tags)
    tags.where.not(tags: '').pluck(:tags).map(&:split).flatten
        .group_by { |i| i }
        .map { |k, v| [k, v.size] }
        .reject { |_k, v| v <= 3 }
        .sort { |t| -t[1] }
  end
end

app/views/tags/index.html.haml
%h2
  %em.fa.fa-tags
  = title t '.title'

- @tags.each do |tag|
  %span.tag(class="size_#{Math.log2(tag[1]).to_i}")
    = link_to tag[0], tag_path(tag[0])

%p=t '.limited'

app/views/tags/show.html.haml
%h2
  = t '.title'
  «
  %em= params[:id]
  »

%nav
  = link_to tags_path, class: :back do
    %em.fa.fa-arrow-left
    = Event.human_attribute_name(:tag).pluralize
  \/
  = link_to events_path tag: params[:id] do
    %em.fa.fa-calendar
    Agenda
  \/
  = link_to events_path format: :rss, tag: params[:id] do
    %em.fa.fa-rss
    RSS
  \/
  = link_to events_path format: :ics, tag: params[:id] do
    %em.fa.fa-th-list
    iCal
  \/
  = link_to maps_path tag: params[:id] do
    %em.fa.fa-map-marker
    OpenStreetMap
  \/
  = link_to maps_path format: :json, tag: params[:id] do
    %em.fa.fa-dot-circle-o
    GeoJSON

- if @events_future.any? || @events_past.any?
  %fieldset
    %legend
      %em.fa.fa-calendar
      = Event.model_name.human.pluralize
    - if @events_future.any?
      %h3=raw t 'future', count: @events_future.count
      %ul.fa-ul
        - @events_future.order('start_time asc').each do |event|
          %li
            = link_to event do
              - if event.locality?
                %em.locality.fa-li.fa.fa-globe(title="#{Event.human_attribute_name :locality} #{t 'attributes.locality_1'}")
              - else
                %em.locality.fa-li.fa.fa-shield(title="#{Event.human_attribute_name :locality} #{t 'attributes.locality_0'}")
              %em.city= event.city
              = event.title
            .date= display_date event

    - if @events_past.any?
      %h3=raw t 'past', count: @events_past.count
      %ul.fa-ul
        - @events_past.order('start_time desc').each do |event|
          %li
            = link_to event do
              - if event.locality?
                %em.locality.fa-li.fa.fa-globe(title="#{Event.human_attribute_name :locality} #{t 'attributes.locality_1'}")
              - else
                %em.locality.fa-li.fa.fa-shield(title="#{Event.human_attribute_name :locality} #{t 'attributes.locality_0'}")
              %em.city= event.city
              = event.title
            .date= display_date event

#map.events(data-url="#{maps_path format: :json, tag: params[:id]}")